'use client'
import {useEffect,useState} from 'react'
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8001'
type Item={id:number;name:string;description:string;price:number;image_url?:string}; type Cart=Record<number,number>
export default function Order({params}:{params:{token:string}}){
 const[data,setData]=useState<any>();const[cart,setCart]=useState<Cart>({});const[placed,setPlaced]=useState<any>();const[error,setError]=useState('');const[name,setName]=useState('');const[phone,setPhone]=useState('');const[session,setSession]=useState('');const[busy,setBusy]=useState(false);const[showCart,setShowCart]=useState(false)
 useEffect(()=>{fetch(`${API}/api/public/tables/${params.token}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{setData(d);const saved=sessionStorage.getItem(`cafeflow:${params.token}`);const savedName=sessionStorage.getItem(`cafeflow-name:${params.token}`);if(saved){setSession(saved);if(savedName)setName(savedName)}}).catch(()=>setError('This table link is no longer active.'))},[params.token])
 if(error)return <main className="shell"><div className="panel"><h1>Sorry, we can&apos;t open this table</h1><p>{error}</p></div></main>;if(!data)return <main className="shell"><p>Loading menu...</p></main>
 const items=data.categories.flatMap((c:any)=>c.items) as Item[];const count=Object.values(cart).reduce((a,b)=>a+b,0);const subtotal=items.reduce((s,i)=>s+i.price*(cart[i.id]||0),0);const add=(id:number)=>setCart(c=>({...c,[id]:(c[id]||0)+1}))
 async function startSession(e:any){e.preventDefault();setBusy(true);setError('');const r=await fetch(`${API}/api/public/tables/${params.token}/session`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,phone})});if(r.ok){const d=await r.json();setSession(d.session_token);sessionStorage.setItem(`cafeflow:${params.token}`,d.session_token);sessionStorage.setItem(`cafeflow-name:${params.token}`,name.trim())}else{const d=await r.json().catch(()=>({}));setError(d.detail||'Please enter a valid name and phone number.')}setBusy(false)}
 async function checkout(){const lines=Object.entries(cart).filter(([,q])=>q>0).map(([item_id,quantity])=>({item_id:Number(item_id),quantity}));const r=await fetch(`${API}/api/public/orders`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({table_token:params.token,session_token:session,items:lines,idempotency_key:crypto.randomUUID()})});if(r.ok){setPlaced(await r.json());setShowCart(false)}else setError('One of your items just became unavailable. Please refresh and try again.')}
 if(placed)return <main className="shell"><div className="topbar"><div className="brand">cafe<span>flow</span></div><span className="pill">{data.table.name}</span></div><div className="hero"><p>Your order is in</p><h1>Thank you - we&apos;re on it.</h1><p>Order <b>#{placed.reference}</b> has been sent to the cafe.</p></div><div className="panel"><h2>Order summary</h2>{placed.items.map((i:any)=><p key={i.name}>{i.name} x {i.quantity}<strong style={{float:'right'}}>₹{i.line_total}</strong></p>)}<hr/><p><strong>Total</strong><strong style={{float:'right'}}>₹{placed.total}</strong></p></div></main>
 if(!session)return <main className="shell"><div className="topbar"><div className="brand">cafe<span>flow</span></div><span className="pill">{data.table.name} · Dine in</span></div><div className="hero"><p>Welcome to CafeFlow</p><h1>What should we call you?</h1><p>We&apos;ll use this to bring your order to the right table. No password or OTP needed.</p></div><form className="panel" onSubmit={startSession}><label>Your name</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Aanya Sharma" required minLength={2}/><label>Phone number</label><input className="input" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="e.g. +91 98765 43210" required minLength={7}/>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Opening menu...':'Continue to menu'}</button></form></main>
 return <main className="shell"><div className="topbar"><div className="brand">cafe<span>flow</span></div><span className="pill">{data.table.name} · Dine in</span></div><section className="hero"><p>Good food, good company</p><h1>Take a little time for something delicious.</h1><p>Hi {name||'there'} - order from your table and we&apos;ll bring it right over.</p></section>{data.categories.map((c:any)=><section key={c.id}><h2 className="category">{c.name}</h2><div className="menu-grid">{c.items.map((i:Item)=><article className="card" key={i.id}>{i.image_url&&<img src={i.image_url} alt=""/>}<div className="card-body"><h3>{i.name}</h3><div className="description">{i.description}</div><div className="price-row"><span className="price">₹{i.price}</span><button className="add" onClick={()=>add(i.id)}>Add {cart[i.id]?`· ${cart[i.id]}`:''}</button></div></div></article>)}</div></section>)}{count>0&&<button className="cart" onClick={()=>setShowCart(true)}>View order · {count} items · ₹{subtotal}</button>}{showCart&&<aside className="cart-panel"><div className="topbar"><h2 style={{margin:0}}>Your order</h2><button className="pill" onClick={()=>setShowCart(false)}>Close</button></div>{items.filter(i=>cart[i.id]).map(i=><div className="cart-line" key={i.id}><div><strong>{i.name}</strong><div>₹{i.price} each</div></div><div className="quantity"><button onClick={()=>setCart(c=>({...c,[i.id]:Math.max(0,(c[i.id]||0)-1)}))}>-</button><strong>{cart[i.id]}</strong><button onClick={()=>add(i.id)}>+</button></div></div>)}<p><strong>Total</strong><strong style={{float:'right'}}>₹{subtotal}</strong></p><div className="cart-actions"><button className="primary" onClick={checkout}>Place order</button></div></aside>}</main>
}
