import enum, secrets
from datetime import datetime, timezone
from sqlalchemy import String, Integer, Boolean, DateTime, ForeignKey, Numeric, Enum, CheckConstraint, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .db import Base
def now(): return datetime.now(timezone.utc)
class Role(str, enum.Enum): ADMIN="ADMIN"
class OrderStatus(str, enum.Enum): PLACED="PLACED"; ACCEPTED="ACCEPTED"; PREPARING="PREPARING"; READY="READY"; COMPLETED="COMPLETED"; CANCELLED="CANCELLED"
class User(Base):
    __tablename__="users"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(120)); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[Role]=mapped_column(Enum(Role),default=Role.ADMIN); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class CafeTable(Base):
    __tablename__="cafe_tables"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(80)); qr_token:Mapped[str]=mapped_column(String(96),unique=True,index=True,default=lambda:secrets.token_urlsafe(32)); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class Category(Base):
    __tablename__="categories"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String(80),unique=True); description:Mapped[str]=mapped_column(Text,default=""); active:Mapped[bool]=mapped_column(Boolean,default=True); items=relationship("MenuItem",back_populates="category")
class MenuItem(Base):
    __tablename__="menu_items"; id:Mapped[int]=mapped_column(primary_key=True); category_id:Mapped[int]=mapped_column(ForeignKey("categories.id")); name:Mapped[str]=mapped_column(String(120)); description:Mapped[str]=mapped_column(Text,default=""); price:Mapped[float]=mapped_column(Numeric(10,2)); image_url:Mapped[str|None]=mapped_column(String(500)); available:Mapped[bool]=mapped_column(Boolean,default=True); active:Mapped[bool]=mapped_column(Boolean,default=True); category=relationship("Category",back_populates="items"); __table_args__=(CheckConstraint("price >= 0"),)
class CustomerSession(Base):
    __tablename__="customer_sessions"; id:Mapped[int]=mapped_column(primary_key=True); session_token:Mapped[str]=mapped_column(String(96),unique=True,index=True); table_id:Mapped[int]=mapped_column(ForeignKey("cafe_tables.id")); customer_name:Mapped[str]=mapped_column(String(100)); customer_phone:Mapped[str]=mapped_column(String(32)); active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); table=relationship("CafeTable")
class Order(Base):
    __tablename__="orders"; id:Mapped[int]=mapped_column(primary_key=True); reference:Mapped[str]=mapped_column(String(20),unique=True,index=True); table_id:Mapped[int]=mapped_column(ForeignKey("cafe_tables.id")); customer_session_id:Mapped[int]=mapped_column(ForeignKey("customer_sessions.id")); customer_name:Mapped[str]=mapped_column(String(100)); customer_phone:Mapped[str]=mapped_column(String(32)); status:Mapped[OrderStatus]=mapped_column(Enum(OrderStatus),default=OrderStatus.PLACED,index=True); subtotal:Mapped[float]=mapped_column(Numeric(10,2)); total:Mapped[float]=mapped_column(Numeric(10,2)); idempotency_key:Mapped[str]=mapped_column(String(120),unique=True,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now); table=relationship("CafeTable"); customer_session=relationship("CustomerSession"); items=relationship("OrderItem",back_populates="order",cascade="all, delete-orphan")
class OrderItem(Base):
    __tablename__="order_items"; id:Mapped[int]=mapped_column(primary_key=True); order_id:Mapped[int]=mapped_column(ForeignKey("orders.id",ondelete="CASCADE")); menu_item_id:Mapped[int]=mapped_column(ForeignKey("menu_items.id")); item_name_snapshot:Mapped[str]=mapped_column(String(120)); unit_price_snapshot:Mapped[float]=mapped_column(Numeric(10,2)); quantity:Mapped[int]=mapped_column(Integer); line_total:Mapped[float]=mapped_column(Numeric(10,2)); order=relationship("Order",back_populates="items"); __table_args__=(CheckConstraint("quantity > 0"),)
